# write an program will take tow input from user an dthen perform diifernt operation
#   * , / , + , - , % , // 

#taking 2 input number from user 
int() # remeber
num1 = int(input("ENTER 1 NUMBER = ") ) #this is String remeber now i will make another method to convert string into integer before save it in varobale 
num2 = int(input("ENTER 2 NUMBER = "))

#perfrom operations
print("tis is our 1 assignment one of python")
print("the  multiplicatuon of two nuber is " , num1 * num2)
print("the divided  of two nuber is " , num1 / num2) # in decimal point
print("the addition  of two nuber is " , num1 + num2)
print("the subtraction  of two nuber is " , num1 - num2)
print("the reminder  of two nuber is " , num1 % num2)
print("the  divided of two nuber is " , num1 // num2)# without decimal point